options:
  substitution_option: ALLOW_LOOSE
substitutions:
  _SERVICE_NAME: cold-harbour-web
  _REGION: europe-north1
  _PROJECT_NUMBER: '471500379526'
  # Secret Manager IDs must match the secret names shown in console:
  # CF_ACCESS_CLIENT_ID, CF_ACCESS_CLIENT_SECRET, POSTGRESQL_LIVE_CONN_STRING, TIMESCALE_LIVE_CONN_STRING
  _DB_PG_SECRET: POSTGRESQL_LIVE_CONN_STRING
  _DB_TS_SECRET: TIMESCALE_LIVE_CONN_STRING
  _CF_CLIENT_ID_SECRET: CF_ACCESS_CLIENT_ID
  _CF_CLIENT_SECRET_SECRET: CF_ACCESS_CLIENT_SECRET
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
    - .
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - run
    - deploy
    - '${_SERVICE_NAME}'
    - '--region=${_REGION}'
    - '--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--set-secrets=POSTGRESQL_LIVE_CONN_STRING=projects/${_PROJECT_NUMBER}/secrets/${_DB_PG_SECRET}:latest'
    - '--set-secrets=TIMESCALE_LIVE_CONN_STRING=projects/${_PROJECT_NUMBER}/secrets/${_DB_TS_SECRET}:latest'
    - '--set-secrets=CF_ACCESS_CLIENT_ID=projects/${_PROJECT_NUMBER}/secrets/${_CF_CLIENT_ID_SECRET}:latest'
    - '--set-secrets=CF_ACCESS_CLIENT_SECRET=projects/${_PROJECT_NUMBER}/secrets/${_CF_CLIENT_SECRET_SECRET}:latest'
images:
- 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
